interface OdptBase {
  // JSON-LD仕様に基づく @context のURL
  "@context": string;
  // 固有識別子(ucode)
  "@id": string;
  // クラス指定
  "@type": string;
  // データ生成日時（ISO8601 日付時刻形式）
  "dc:date"?: string;
  // 固有識別子。
  "owl:SameAs": string;
}

interface MultiLang {
  ja: string;
  en: string;
}

interface Train extends OdptBase {
  // データ保証期限（ISO8601 日付時刻形式）
  "dct:valid"?: string;
  // 運行会社を表すID (odpt:Operatorのowl:sameAs)
  "odpt:operator": string;
  // 鉄道路線を表すID (odpt:Railwayのowl:sameAs)
  "odpt:railway": string;
  // 進行方向を表すID (odpt:RailDirectionのowl:sameAs)
  "odpt:railDirection"?: string;
  // 列車番号
  "odpt:trainNumber": string;
  // 列車種別 (odpt:TrainTypeのowl:sameAs)
  "odpt:trainType"?: string;
  // 編成の名称・愛称のリスト（多言語対応）
  "odpt:trainName"?: MultiLang;
  // 列車が直前に出た駅、あるいは停車中の駅を表すID (odpt:Stationのowl:sameAs) を格納
  "odpt:fromStation"?: string;
  // 列車が向かっている駅を表すID (odpt:Stationのowl:sameAs) を格納
  "odpt:toStation"?: string | null;
  // 列車の始発駅を表すID (odpt:Stationのowl:sameAs) のリスト
  "odpt:originStation"?: string[];
  // 列車の終着駅(行先駅)を表すID (odpt:Stationのowl:sameAs) のリスト
  "odpt:destinationStation"?: string[];
  // 列車の経由駅を表すID (odpt:Stationのowl:sameAs) のリスト
  "odpt:viaStation"?: string[];
  // 列車の経由路線を表すID (odpt:Railwayのowl:sameAs)のリスト
  "odpt:viaRailway"?: string[];
  // 車両の所属会社を表すID (odpt:Operatorのowl:sameAs)
  "odpt:trainOwner"?: string;
  // 路線内の列車順序
  "odpt:index"?: number;
  // 遅延時間（秒）
  "odpt:delay"?: number;
  // 車両数
  "odpt:carComposition"?: number;
  // その他プロパティとして定義されていない注釈情報の自然言語による記載（多言語対応）
  "odpt:note"?: MultiLang;
}

// Generated by https://quicktype.io

export interface Odpt {
  "@id": string;
  "@type": "odpt:Train";
  "dc:date": string;
  "@context": string;
  "dct:valid": string;
  "odpt:delay": number;
  "owl:sameAs": string;
  "odpt:railway": "odpt.Railway:Toei.Shinjuku";
  "odpt:operator": OdptOperator;
  "odpt:toStation": null | string;
  "odpt:trainType": OdptTrainType;
  "odpt:trainOwner": OdptOperator;
  "odpt:fromStation": string;
  "odpt:trainNumber": string;
  "odpt:originStation": string[];
  "odpt:railDirection": OdptDirection;
  "odpt:destinationStation": OdptDestinationStation[];
}

export enum OdptDestinationStation {
  Sasazuka = "odpt.Station:Keio.KeioNew.Sasazuka",
  Sakurajosui = "odpt.Station:Keio.KeioNew.Sakurajosui",
  HachimanYama = "odpt.Station:Keio.KeioNew.HachimanYama",
  Tsutsujigaoka = "odpt.Station:Keio.KeioNew.Tsutsujigaoka",
  KeioTamaCenter = "odpt.Station:Keio.Sagamihara.KeioTamaCenter",
  Hashimoto = "odpt.Station:Keio.Sagamihara.Hashimoto",
  Takahatafudo = "odpt.Station:Keio.Takao.Takahatafudo",
  TamaDobutsukoen = "odpt.Station:Keio.Takao.TamaDobutsukoen",
  Takaosanguchi = "odpt.Station:Keio.Takao.Takaosanguchi",
  KeioHachioji = "odpt.Station:Keio.Takao.KeioHachioji",
  Motoyawata = "odpt.Station:Toei.Shinjuku.Motoyawata",
  Mizue = "odpt.Station:Toei.Shinjuku.Mizue",
  Ojima = "odpt.Station:Toei.Shinjuku.Ojima",
  Iwamotocho = "odpt.Station:Toei.Shinjuku.Iwamotocho",
}

export enum OdptOperator {
  Keio = "odpt.Operator:Keio",
  Toei = "odpt.Operator:Toei",
}

export enum OdptDirection {
  E = "odpt.RailDirection:Eastbound",
  W = "odpt.RailDirection:Westbound",
}

export enum OdptTrainType {
  Local = "odpt.TrainType:Toei.Local",
  Express = "odpt.TrainType:Toei.Express",
}

export default Train;
