name: Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: su8ru/kostl-next/server-prod-image

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    environment:
      name: Server
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          default_branch: main
          tags: latest
          workdir: server
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, DEPLOY_DIR
          script: |
            cd $DEPLOY_DIR
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker compose pull
            docker compose up -d
