name: Test Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      API_SERVER_PORT: 8080
      API_ORIGIN: http://localhost:8080
      API_BASE_PATH: /
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: client-yarn-cache
        with:
          path: "node_modules"
          key: client-yarn-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v2
        id: server-yarn-cache
        with:
          path: "server/node_modules"
          key: server-yarn-${{ hashFiles('server/yarn.lock') }}
      - run: yarn install
        if: steps.client-yarn-cache.outputs.cache-hit != 'true'
      - run: yarn install --cwd server
        if: steps.server-yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run lint
      - run: |
          sudo systemctl start mysql.service
          echo "API_DATABASE_URL=mysql://root:root@localhost:3306/test" > server/prisma/.env
      - run: yarn run typecheck
